version: 2
jobs:
  build:
    working_directory: ~/react-360
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: yarn
      - run: yarn build
  flow:
    working_directory: ~/react-360
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: yarn
      - run: yarn flow
  test-unit:
    working_directory: ~/react-360
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: yarn
      - run: yarn build
      - run: yarn test
  render-tests:
    working_directory: ~/react-360/render-tests
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: yarn
      - run: yarn build

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test-unit:
          requires:
            - build
      - render-tests:
          requires:
            - build
      - flow
